# permissions for end users to edit democlusterconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: democlusterconfigmap-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: configmap-operator
    app.kubernetes.io/part-of: configmap-operator
    app.kubernetes.io/managed-by: kustomize
  name: democlusterconfigmap-editor-role
rules:
- apiGroups:
  - demo.github.com
  resources:
  - democlusterconfigmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.github.com
  resources:
  - democlusterconfigmaps/status
  verbs:
  - get
